# Generated by Django 5.2.5 on 2026-01-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_country_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('monitoring', 'Monitoring'), ('analyzing', 'Analyzing'), ('potential', 'Potential')], default='analyzing', max_length=20),
        ),
    ]
