# Generated by Django 5.2.5 on 2026-01-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteexploration',
            old_name='diameter_max',
            new_name='max_minigrid_network_distance',
        ),
        migrations.RenameField(
            model_name='siteexploration',
            old_name='distance_from_grid_min',
            new_name='min_distance_from_grid',
        ),
        migrations.RenameField(
            model_name='siteexploration',
            old_name='match_distance_max',
            new_name='min_distance_to_an_existing_minigrid',
        ),
        migrations.RenameField(
            model_name='siteexploration',
            old_name='consumer_count_min',
            new_name='min_num_of_consumers',
        ),
        migrations.AddField(
            model_name='siteexploration',
            name='province',
            field=models.CharField(blank=True, default='', max_length=51),
        ),
    ]
