# Generated by Django 5.2.5 on 2026-01-29 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_rename_diameter_max_siteexploration_max_minigrid_network_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tax',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
