# Generated by Django 5.2.5 on 2026-02-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_monitoringdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='monitoring_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
